### PR TITLE
enhance: other URL schemes

### LINKED ISSUE #72: other URL schemes
## 💡 Summary

Only `http` or `https` URL schemes are recognized. According to the WHATWG specification, many more schemes are possible (`mailto`, `irc`, `gemini`, ...): `[a-zA-Z] [-a-zA-Z0-9+.]* ":"`

👉 [current specification about URL scheme](https://url.spec.whatwg.org/#url-scheme-string) ([⎇日本語](https://triple-underscore.github.io/URL-ja.html#url-scheme-string))

Understanding all possible URLs in normal text could lead to too many links. My idea would be to understand other URLs **only** in `altUrlFormat` and `linkUrl` (but **not** in `urlFormat`).

## 🙂 Expected Behavior

```markdown
oops:url
<gemini://example.com>
[send email](mailto:nobody@example.com?subject=test)
```
&darr;
```JSON
[
  {
    "type": "text",
    "props": {
      "text": "oops:url"
    }
  },
  {
    "type": "url",
    "props": {
      "url": "gemini://example.com",
      "brackets": true
    }
  },
  {
    "type": "link",
    "props": {
      "silent": false,
      "url": "mailto:nobody@example.com?subject=test"
    },
    "children": [
      {
        "type": "text",
        "props": { "text": "send mail" }
      }
    ]
  }
]
```

### PR DESCRIPTION
**Pull request by Johann150**
resolves #72

> - CHANGELOG.mdに変更点を追記してください。リファクタリングなど、利用者に影響を与えない変更についてはこの限りではありません。
> - Please add the summary of the changes to CHANGELOG.md. However, this is not necessary for changes that do not affect the users, such as refactoring.

👀 CHANGELOG.md ?

- `npm run test` ✅
- `npm run lint` ✅
- `npm run api` ✅

### CODE REVIEW

**Comment by syuilo** [comment]
🙏

**Comment by rinsuki** [comment]
wait, I think, after this pull-request merged, it can XSS by like [LETS GET ONE BILLION DALLERS HERE](javascript:alert(1)). we should add validate that it is known safe URL schemes.

**Comment by Johann150** [comment]
😨 You are right.
Are there any other URL schemes apart from `javascript` that you think are dangerous? Because I think it would be easier to only forbey specific URL schemes (like javascript) than to only allow specific URL schemes. Otherwise that would mean that there could be many "please add protocol xyz" issues in the future.

**Comment by rinsuki** [comment]
I don't know, but any URL schemes has a possibility dangerous in the future or specific environment. I prefer allow-list because deny-list may be bypassed if implementation is vulnerable for hacky escape or other something. I think "got many 'please add XXXX protocol' issue" is better than possibility vulnerable.

**Comment by Johann150** [comment]
Hmm, or maybe a [content security policy](https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP) could avoid such things.

```html
<meta http-equiv="Content-Security-Policy" content="script-src 'self';">
```
This would allow JavaScript from `javascript:` and even `data:` etc. URLs: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/script-src

**Comment by Johann150** [comment]
> [...] may be bypassed if implementation is vulnerable for hacky escape or other something.

😕 If the browser is vulnerable, I don't think it would be MFM's or Misskey's responsibility to fix it?

**Comment by rinsuki** [comment]
yeah, If library users are using CSP _correctly_, XSS are never executed. but we shouldn't expect that 100% library users are using CSP. actually I think 99% of users are misskey-dev/misskey, but some clients can using this library too. and imagine what occured if this library used in Electron apps without CSP and user clicked javascript link...

**Comment by rinsuki** [comment]
> > [...] may be bypassed if implementation is vulnerable for hacky escape or other something.
> 
> 😕 If the browser is vulnerable, I don't think it would be MFM's or Misskey's responsibility to fix it?

"implementation" of `implementation is vulnerable` means mfm.js allow-list implemention, not browser one.

**Comment by marihachi** [comment]
セキュリティの側面から見てなかったので、助かった。
使用可能なスキーマをホワイトリストにする方が良いかもしれない。

また、ユーザーアプリ側からホワイトリストをカスタマイズ可能にすることもできそう。(許可するかどうかは要検討)

このPRの内容からは若干反れるので、別のissueとした方が良さそう。

**Comment by syuilo** [comment]
うん、私もセキュリティの観点はすっぽり抜けてた
ありがとうございます🙏

**Comment by syuilo** [comment]
In the future, we may allow schemas other than http/https in a whitelist or blacklist format, but for now, we need to revert for safety. 🙏🏻

**Pull request merged**
